### ISSUE TITLE
Syntax hole definition vector question

### ISSUE THREAD

**Issue by vitvly** [awto/mixfix-clj#1]
Hi Vitaliy!

First of all, thank you for a great library! For a great majority of my use cases, the examples provided by you in README.md are quite sufficient. However, i am struggling when writing some operators of my own. Can you please clarify a bit the following lines from README:

`empty` - means same precedence level as its operator
`number` - specifies any precedence explicitly
`+` - precedence is the same as the operator's one
`assoc` - will unwrap sub-form if it has same head symbol as the operator
`id <value>` - for assoc operators will treat as identity for the operation, by default nil.

By this description, what is the difference between `empty` and `+`? I've noticed that if i modify the definition of `+` in one of your examples to `(m/op 400 + [[] + []])`, ambiguity errors appear. So there must be some difference. And another question is: what is the identity of the operation referred to in `id` description?

Thanks again,
Vitaliy.

**Comment by awto** [comment]
Hi Vitaliy

thanks for reporting the problem in README, I have pushed the fix, `+` is of course for rising precedence level, so 

``` clojure
(m/op 400 + [[] + [+]])
```

is the same as

``` clojure
(m/op 400 + [[400] + [401]])
```

providing information if either that operator is left/right or non-associative. If there is no `+` it is non-associative, and `1 + 2 + 3` may be parsed either as `(1 + 2) + 3` or `1 + (2 + 3)`. This is ambiguous. 

Identity means unit for the operation, applying the operation to identity value and any other argument returns this other argument, for example for `+` it is 0, and for `*` it is 1. For some custom operator this may be something else.

**Comment by vitvly** [comment]
Thank you so much! This is much more clear now!
